apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-c1a2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-c1a2
    app.kubernetes.io/part-of: ci1t-830-0038-app
  name: devfile-sample-c1a2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-c1a2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-c1a2
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0038-tenant/ci1t-830-0038-app/devfile-sample-c1a2@sha256:bc8d760ccadfe3117d24ac594a43c3a9a7c06f394470305fc97e2b74bff81266
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
